enpal_assessment_project:
# default target is the dev environment, change --target prod for production -- in case we have two env for dbt worflow
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      dbname: "{{ env_var('DBT_TEST_DBNAME') }}"
      user: "{{ env_var('DBT_TEST_USER') }}"
      pass: "{{ env_var('DBT_TEST_PASSWORD') }}"
      schema: dev_analytics
      keepalives: 1             # enables TCP keepalive
      keepalives_idle: 60       # seconds before keepalive ping
      connect_timeout: 10       # seconds for connection timeout
      retries: 3                # number of retries for failed queries
      threads: 4                # dbt can run multiple models in parallel
      application_name: "dbt_enpal_dev"
      sslmode: prefer           # tries SSL if available, otherwise falls back to plain text
    prod:
      type: postgres
      host: 127.0.0.1
      port: 5432
      dbname: "{{ env_var('DBT_PROD_DBNAME') }}"
      user: "{{ env_var('DBT_PROD_USER') }}"
      pass: "{{ env_var('DBT_PROD_PASSWORD') }}"
      schema: analytics
      keepalives: 1
      keepalives_idle: 60
      connect_timeout: 10
      retries: 1
      threads: 4
      application_name: "dbt_enpal"
      sslmode: require            # Always use SSL. Fail if the server doesn’t support it.